// src/components/Drawer/Bubbles.tsx
import { random, animate, stagger } from "animejs";
import { For, onMount } from "solid-js";

const bubbles = Array(10)
  .fill(true)
  .map(() => ({
    r: random(2, 5),
    cx: 50 + "%",
  }));

export default function Bubbles() {
  console.log(bubbles);

  onMount(() => {
    animate(".bubble", {
      autoplay: true,
      x: [
        {
          to: () => random(-50, 50) + "%",
          ease: "inOutSine",
        },
        {
          to: () => random(-50, 50) + "%",
          ease: "inOutSine",
        },
      ],
      y: [{ from: "10%", to: "-100%", ease: "inOutSine" }],
      delay: stagger(700, { start: 0 }),
      duration: 3000,
      loop: true,
    });
  });

  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="pointer-events-none absolute h-full w-full border-2 fill-white/65"
    >
      <For each={bubbles}>
        {(bubble) => (
          <circle
            class="bubble"
            cx={bubble.cx}
            cy="95%"
            r={bubble.r}
            stroke="none"
          />
        )}
      </For>
    </svg>
  );
}

// src/components/Nav/Sidebar/Bubbles.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import anime from 'animejs';

	const bubbleAmount = 50;

	const bubbles = Array(bubbleAmount)
		.fill(true)
		.map((b, i) => ({
			r: anime.random(3, 5),
			cx: anime.random(15, 90) + '%'
		}));

	onMount(() => {
		anime({
			targets: '.bubble',
			autoplay: true,
			translateX: {
				value: [0, '20%', 0],
				easing: 'easeOutQuad',
				duration: 3000
			},
			translateY: ['10%', '-100%'],
			delay: (e, i) => i * 1000,
			loop: true,
			duration: () => anime.random(3000, 5000),
			easing: 'easeInQuad'
		});
	});
</script>

<svg xmlns="http://www.w3.org/2000/svg" class="bubbles">
	{#each bubbles as bubble}
		<circle class="bubble" cx={bubble.cx} cy="95%" r={bubble.r} stroke="none" />
	{/each}
</svg>

<style>
	svg.bubbles {
		@apply absolute inset-0 h-full pointer-events-none fill-white opacity-65;
	}
</style>
