// src/components/Drawer/Item.tsx
import { JSX } from "solid-js";

interface Props {
  onClick: (e: MouseEvent) => void;
  label?: string;
}

export default function Item({ onClick, label }: Props) {
  if (!label) return null;
  return (
    <li>
      <a
        href="#"
        onClick={onClick}
        class="group relative block py-2 tracking-widest whitespace-nowrap ring-0 outline-none"
      >
        {label
          .split("")
          .map((letter, i) =>
            letter === " " ? (
              " "
            ) : (
              <span class="inline-block transition-transform group-hover:translate-y-2 group-hover:rotate-12 group-hover:odd:-translate-y-2 group-hover:odd:-rotate-12">
                {i === 0 ? letter.toUpperCase() : letter}
              </span>
            ),
          )}
      </a>
    </li>
  );
}

// src/components/Nav/Sidebar/Item.svelte
<script lang="ts">
	import { scrollTo } from '../../../actions';

	export let id: string;
	export let label: string;
	export let onNavigation: () => void;
	export let offset: number;

</script>

<li>
	<a href={`#${id}`} use:scrollTo={{ offset, onStart: onNavigation }}>
		{#each label.split('') as letter, i}
			{#if letter === ' '}
				{letter}
			{:else}
				<span>
					{letter}
				</span>
			{/if}
		{/each}
	</a>
</li>

<style>
	a {
		@apply relative block py-2 tracking-widest;
		@apply ring-0 outline-none;
		@apply whitespace-nowrap;
	}
	span {
		@apply inline-block transition-transform;
	}
	a:hover span,
	a:focus span {
		@apply translate-y-2 rotate-12;
	}
	a:hover span:nth-child(odd),
	a:focus span:nth-child(odd) {
		@apply -translate-y-2 -rotate-12;
	}
</style>
