// src/components/Button.svelte
<script>
    export let secondary = false;
    // export let ;
</script>

<button class:secondary>
    <slot />
</button>

<style>
    button {
        @apply bg-green text-black font-bold text-2xl px-6 py-2;
        @apply shadow rounded-sm border-2 border-black;
        @apply hover:shadow-lg focus:shadow-lg outline-none;
        @apply active:shadow-sm;
    }

    button.secondary {
        @apply bg-gray-light text-black border-2;
    }
</style>

// src/components/Button.tsx
import clsx from "clsx";
import { JSX } from "solid-js";

interface Props extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary";
  onClick?: () => void;
  children: JSX.Element;
}

export default function Button({
  variant = "primary",
  onClick,
  children,
  class: className,
  ...rest
}: Props) {
  return (
    <button
      class={clsx(
        "bg-glb-green shadow-glb-hard cursor-pointer border-2 border-black px-6 py-2 text-2xl font-bold text-black outline-none",
        "hover:shadow-glb-hard-lg focus:shadow-glb-hard-lg active:shadow-glb-hard-sm",
        "transition-shadow",
        {
          "bg-gray-light text-black": variant === "secondary",
        },
        className,
      )}
      onClick={onClick}
      {...rest}
    >
      {children}
    </button>
  );
}
