// src/components/Nav/Bubbles.svelte
<script>
	import { onMount } from 'svelte';
	import anime from 'animejs';

	const bubbleAmount = 20;

	const bubbles = Array(bubbleAmount)
		.fill(true)
		.map((b, i) => ({
			r: anime.random(3, 5),
			cx: anime.random(15, 90) + '%'
		}));

	onMount(() => {
		anime({
			targets: '.bubble',
			autoplay: true,
			translateX: {
				value: [0, '20%', 0],
				easing: 'easeOutQuad',
				duration: 3000
			},
			translateY: ['10%', '-100%'],
			delay: (e, i) => i * 1000,
			loop: true,
			duration: () => anime.random(3000, 5000),
			easing: 'easeInQuad'
		});
	});
</script>

<svg xmlns="http://www.w3.org/2000/svg" class="bubbles">
	{#each bubbles as bubble}
		<circle class="bubble" cx={bubble.cx} cy="95%" r={bubble.r} stroke="none" />
	{/each}
</svg>

<style>
	svg.bubbles {
		@apply absolute w-full h-full pointer-events-none fill-white opacity-65;
	}
</style>

// src/components/Drawer/animations/Bubbles.tsx
import { For } from "solid-js";
import s from "./Bubbles.module.css";

const singleDuration = 3000;
const singleDelay = singleDuration / 3;
const bubbleAmount = singleDuration / singleDelay;
const bubbleStart = 110;

const getCx = () => Math.random() * 100 + "%";
const getR = () => `${Math.random() * (5 - 2) + 2}`;
const getWiggle = () => Math.random() * (15 - 1) + 1 + "px";

const bubbles = Array.from({ length: bubbleAmount }, () => ({
  r: getR(),
  cx: getCx(),
  cy: bubbleStart + "%",
}));

export default function Bubbles() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="pointer-events-none absolute h-full w-full fill-white/65"
    >
      <For each={bubbles}>
        {(bubble, i) => {
          return (
            <circle
              class={s.bubble}
              cx={bubble.cx}
              cy={bubble.cy}
              r={bubble.r}
              style={{
                "animation-delay": i() * singleDelay + "ms",
              }}
              onAnimationIteration={(e) => {
                const t = e.currentTarget;
                t.style.cx = getCx();
                t.style.r = getR();
                t.style.setProperty("--wiggle", getWiggle());
              }}
            />
          );
        }}
      </For>
    </svg>
  );
}
